version: '3'
services:
 backend:
   image: node:20-alpine
   volumes:
     - ./backend:/app
   working_dir: /app
   command: sh -c "npm install && npm start"
   ports:
     - 3000:3000
 frontend:
   image: node:20-alpine
   volumes:
     - ./frontend:/app
   working_dir: /app
   command: sh -c "npm install && npm start"
   ports:
     - 8080:8080
